name: Playwright Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Checkout the code
      - uses: actions/checkout@v4

      # Step 2: Set up Node.js environment with the latest LTS version
      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      # Step 3: Install dependencies using npm ci (to install from package-lock.json)
      - name: Install dependencies
        run: npm ci

      # Step 4: Install Playwright and the necessary browsers
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      # Step 5: Run Playwright tests
      - name: Run Playwright tests
        run: npx playwright test

      # Step 6: Upload Playwright test reports as artifacts
      - uses: actions/upload-artifact@v4
        if: always()  # Ensure this step runs even if the tests fail
        with:
          name: playwright-report  # Artifact name
          path: playwright-report/  # Path to the Playwright reports folder
          retention-days: 30  # Keep the report for 30 days
